# Define variables
CC = gcc
CFLAGS = -Wall -g        # -Wall for warnings, -g for debugging info
INC_DIR = .              # Our include directory is the current directory

#define targets
# all: calculator

# calculator: main.o, calculator.h
# $(CC) $(CFLAGS) main.o calculator.o -o calculator

# main.o: main.c calculator.h
# $(CC) $(CFLAGS) -I$(INC_DIR) -c main.c

# calculator.o: calculator.c calculator.h
